### ISSUE TITLE
Crash when running app.py

### ISSUE THREAD

**Issue by tuvokki** [tuvokki/data-api#4]
Tried running on windows and got a crash:

```
dataapienv\Scripts\python.exe app.py
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from modules.quotes import QuotesView
  File "c:\meuk\projects\data-api\modules\quotes.py", line 21
    print "This is a test, smile ", quote_id
                                 ^
SyntaxError: Missing parentheses in call to 'print'
```

I'm using the following:

```
dataapienv\Scripts\python.exe --version
Python 3.4.3
```

**Comment by tuvokki** [comment]
“SyntaxError: Missing parentheses in call to 'print'” is a new error message that was added in Python 3.4.2 to help users that are trying to follow a Python 2 tutorial while running Python 3.

In Python 3, printing values changed from being a distinct statement to being an ordinary function call, so it now needs parentheses.
